### ISSUE TITLE
Analysis of large or nested loops

### ISSUE THREAD

**Issue by rasoolmaghareh** [tracer-x/TracerX#254]
I have observed that analysis of benchmarks with the following loops can take a long time:

1- Loops nested for 3 layers or more
2- Loops which iterate for many iterations and have if-statements inside the iterations

Two example benchmarks are `ud` and `compress`.

Some notes to think about:

1- If a loop contains few unsat cores => Inline the loop
2- We need to understand the difference between infeasible path and artificial infeasible path (generated from loop-header false paths)
3- In case a loop is truly complicated nothing can be possibly done.

**Comment by domainexpert** [comment]
@rasoolmaghareh In another project with @Himeshi, we encountered this issue as well. fp-analysis/klee#13 is our current approach to this. Basically we extract the trip count using LLVM's scalar evolution, force the loop to terminate just after 2 iterations, and multiply the analysis result by the trip count.

Regarding your notes:
1. Good idea: this will improve performance as we do not need to test for loop exits. I can see that partial inlining / unrolling can be done, but if one wants to unroll the loop completely, one needs to know the trip count. Example in the TripCounter class of fp-analysis/klee#13.
2. They are treated as the same currently in the implementation, as proofs that generate interpolants.
3. I agree!

**Comment by rasoolmaghareh** [comment]
Thanks for the notes. Do you have an estimate that how much does the approach in [fp-analysis/klee#13](https://github.com/fp-analysis/klee/pull/13) affect the precision?

**Comment by domainexpert** [comment]
@rasoolmaghareh That's a good question. We definitely are approximating the result. Since when the loop is broken, we do not assume anything about the values computed in the result. This is still a work in progress, so we don't have experiments data yet.

**Comment by rasoolmaghareh** [comment]
I see. On WCET I think this idea can cause some inaccuracy as discussed in [EMSOFT'11 paper](http://dl.acm.org/citation.cfm?id=2038692). The other idea can be merging states in the end of the loops. However, we can also explain that this issue is an orthogonal issue and can be addressed by one of these two technologies. Thanks.

**Comment by domainexpert** [comment]
@rasoolmaghareh Thanks for pointing to the paper. If you agree, I would like to keep this issue open for further discussion.
