### ISSUE TITLE
.NET versions

### ISSUE THREAD

**Issue by securigy** [tracer-x/TracerX#387]
I usually use TracerX in .NET Framework project and now it works well with async/await pattern and in .NET 7 app.
However, I am building a library now that also needs to be instrumented and this library supposed to be compatibel both with .NET 7 and .NET Framework. The only solution I could find was suggested by chatGPT that claims that if I build the library for .NET 2.0 Standard then it will be compatible with both (not even 2.1). So that's what I did but then when I added NuGet package I see the warning in Visual Studio under Packages > TracerX-Logger (9.5.0):
_Package 'TracerX-Logger 9.5.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project._

Can I safely ignore this warning?

**Comment by rasoolmaghareh** [comment]
I am not sure if this issue has been written on the correct repo. I think you are referring to TracerX logger and viewer for .NET which is a different project.
