### ISSUE TITLE
State Merging Is Not Handled

### ISSUE THREAD

**Issue by domainexpert** [tracer-x/TracerX#45]
State merging in KLEE causes problems with missing path condition constraints when marking constraints on the path condition on subsumption check (in `SubsumptionTableEntry::subsumed`). This is because the constraints in the unsatisfiability core are from the `ExecutionState` constraints, which, when merging had been done, would contain more constraints than those that can be marked in `PathCondition`. The problem is currently ignored by keeping silent if a constraint in the core does not exist on the path condition.

**Comment by domainexpert** [comment]
@feliciahalim The issue mentioned seems to be not due to state merging but possible disjunctions generated somewhere. State merging in KLEE can only be activated using `-use-merge` or `-use-bump-merge` options, which so far had not been used in the experiments. The effect of state merging for interpolation is, however, worth investigating.

**Comment by feliciahalim** [comment]
@domainexpert Okay, I will investigate further regarding this issue.
