### ISSUE TITLE
Need for WLP to Compute Interpolant

### ISSUE THREAD

**Issue by feliciahalim** [tracer-x/TracerX#74]
I just added a new example in here https://github.com/tracer-x/klee-examples/blob/master/basic/addition_safe10.c , this example is actually the modification of https://github.com/tracer-x/klee-examples/blob/master/basic/addition_safe5.c by re-ordering its addition operation. `Addition_safe5` has 4 subsumptions, while `addition_safe10` has zero subsumption.  This is the snapshot of `addition_safe10.c` :

```
 klee_assume(x <= 0);

  if (p1 > 8)
    x = x + 2;
  else
    x = x + 0;

  if (p2 > 8)
    x = x + 2;
  else
    x = x + 1;

  if (p3 > 8)
    x = x + 2;
  else
    x = x + 1;

  assert(x <= 6);
```

@domainexpert  I think there's opportunity to make subsumption for this case by adding the constraint from the assertion. For example, after we executed the last `IF` condition (`p3`) for both its `false` and `true`, we know that at this point to be in safe condition `x` should be `x <= 4` (can be generated from its assertion `x <=6` and addition operation in `p3`). Therefore, as long as the `x<=4`  still holds before that point, it is still considered as safe and can be subsumed. The idea still rough, it may need further exploration.

**Comment by domainexpert** [comment]
@feliciahalim Very good idea. This is indeed weakest *liberal* precondition (*wlp*)reasoning and worth doing. From [predicate transformer semantics](https://en.wikipedia.org/wiki/Predicate_transformer_semantics) and considering the else branch of the last if conditional, and that `x0 + 2 <= 6` (or just `x <= 6` without the substitution with the function on initial values) is in the core, `wlp(x = x + 1, x <= 6)` equals

`forall x' : x' = x + 1 -> x' <= 6`

which is `x + 1 <= 6` and `x <= 5`. Here, the `__shadow__x` will be stored in the interpolation table (`SubsumptionTableEntry`) with the constraint (something like) `(Sle (Add __shadow__x 1) 6)`. In general, we cannot further simplify this to `(Sle __shadow__x 5)` as this requires computing the inverse of function. In this case the inverse of `f(x) |-> x + 1` function is `g(x) |-> x-1` function, which can very simply be applied to 6 obtaining 5, that is, we compute `x <= 5` from `g(x+1) <= g(6)`, but in general inverse function may not exist. However, whenever we could not compute the inverse, we can store the function itself, as the addition in `(Sle (Add __shadow__x 1) 6)`. In this case, it will be the task of the solver to figure things out.

**Comment by domainexpert** [comment]
@feliciahalim Sorry I closed it by mistake. Pressed the wrong button.

**Comment by domainexpert** [comment]
@feliciahalim In fact, we should not too liberally use 'inverse' function, unless we are sure that it is the true inverse. For example, in bitvector domain `g(x) |-> x - 1` may not be the true inverse of `f(x) |-> x + 1`, when considering overflow/underflow.

**Comment by domainexpert** [comment]
@feliciahalim Another issue is that there is an exponential number of *wlp*s in the program size, as there are exponential number of paths emanating from a particular point. Therefore, the stored interpolant is actually one big conjunction of the interpolants contributed by each path. We could try to simplify the conjunction, however, this is another challenge with no general solution.

**Comment by feliciahalim** [comment]
@domainexpert Thank you very much for the fast and elaborate response. I realize exponential number of `wlps` could be another challenge. We could further analyze and discuss this before actually implementing this.

**Comment by feliciahalim** [comment]
@domainexpert  in the future, we could probably create an option in tracer-x that allow user to select between `sp` (current algorithm) and `wlp`.

**Comment by domainexpert** [comment]
@feliciahalim That's right, or use *wlp* up to bounded depth only (from the end of the trace).

**Comment by domainexpert** [comment]
@feliciahalim An idea is to store backward interpolant only if it's not too big as *w(l)p* results in disjunctions (for *wp*, conjunctions for *wlp*). Ways to mitigate this issue include:
1. Removing irrelevant constraints from the backward interpolant.
2. Replacing the disjunction by an under-approximation, e.g, replacing disjunction with conjunction of the same boolean values, when the resulting conjunction is an interpolant.
3. Use a common *slackening* (*bounds*). For example, the *wlp* of branch 1 and 2 are respectively *x<=3* and *x<=2*. The conjunction is *x<=2*.

An implementation idea is to compute the backward *wlp* whenever there is a proof (that one side of a branch is unreachable), e.g., in `Executor::fork`. This is then stored in the current interpolation tree node (`ITreeNode`). When the node is removed, the combined *wlp* of an `ITreeNode` object is stored in the `SubsumptionTableEntry` object newly created, and the *wlp* is computed for the parent of the removed node.
