### ISSUE TITLE
Designing klee_join

### ISSUE THREAD

**Issue by domainexpert** [tracer-x/TracerX#91]
@feliciahalim To do abstraction at subsumption checkpoint. Here we add a new API, perhaps called `klee_subsume_abstract(name, var1, ..., varN)` specifying a CLP predicate named `name`, with arguments `var1`, ..., `varN`, which are program variables. The assertion does not change the symbolic exploration, however, at the earliest subsumption checkpoint(s) after the call, at the point of checking for subsumption, we check that the CLP predicate `name(var1, ..., varN)` holds instead of checking that the interpolant holds. Credit goes to Joxan Jaffar for the idea.

**Comment by domainexpert** [comment]
@feliciahalim I've thought about a possibly better name for the API instead of the long `klee_subsume_abstract`, that is, `klee_join`. So this joins control flow whenever the CLP recursive predicate is satisfied at call point of the API function. Note that I think now we should check for subsumption at the call site of the API function, which is easier to implement, instead of the "earliest subsumption checkpoint(s) after the call" that I previously mentioned.

**Comment by domainexpert** [comment]
@feliciahalim We need a second version of `klee_join`, where we could specify the CLP(R) file from which to load the predicate definition, if that file has not been loaded previously. Let's call this second version `klee_join_with_library(library_spec, name, var1, ..., varN).` `name`, and `var1, ..., varN` are as previously, but now we have `library_spec`, which is the path of the library.

**Comment by feliciahalim** [comment]
@domainexpert Thanks for the ideas. It looks fine for me. `klee_join` is preferable since it is more compact  than `klee_subsume_abstract`.

**Comment by domainexpert** [comment]
@feliciahalim So, to summarize, so far we agreed on the following:
1. `klee_join` has to be given argument types as part of the API (can this be obtained from varargs mechanism?).
2. Abstraction here is done at the point of storage of a new entry into the subsumption table, via the following steps:
      a. First, check that `interpolant` implies `abstraction`. This is done by CLP(R), and `abstraction` here is a CLP predicate `name(var1, ..., varN)`.
      b. If so, when say `var(abstraction)` is the variables of the `abstraction`, and their primed (ghost) versions are `ghost(abstraction)`, we store `(exists ghost(abstraction) s.t. interpolant[ghost(abstraction)/var(abstraction)]) /\ abstraction`.
3. We use `klee_join` callsite as subsumption checkpoint.

**Comment by feliciahalim** [comment]
@domainexpert Thank you for summarizing the discussion. Would you please inform me about the mechanism to create `abstraction` which is done by CLP(R) ? Thank you.

**Comment by domainexpert** [comment]
@feliciahalim Yes, I forgot to clarify that one. So, the interpolant is the `interpolant` field computed in the constructor of `SubsumptionTableEntry`. This is one big expression (of type `ref<Expr>`). We first translate this expression into CLP(R) format, say the translation result is `clpr(interpolant)`. So here we want to prove `clpr(interpolant) => name(var1, ..., varN)`. This we could do by posing the satisfiability query `clpr(interpolant), not(name(var1, ..., varN))`, to CLP(R) via building a `clpr::CLPQuery` object and pass it to the solver engine using `clpr::CLPEngine::query`. If the result was satisfiable, i.e., `clpr::CLPEngine::hasSolution()` returned true, then we know the implication does not hold. The implication (proof) holds when the query has no solution (`CLPEngine::hasSolution()` is false).

**Comment by domainexpert** [comment]
@feliciahalim In 4153dd8, `klee_join` has been implemented, however, there is a difference to the previous discussion, where a simpler approach has been taken in the following way: attempt to prove the CLP predicate is made whenever `klee_join` is encountered. The first time the proof is successful, the `klee_join` is declared to have been successfully proven before. Subsequent successful proof is considered a subsumption. The new design is simpler. Both the earlier discussed design and this new design results in incomplete analysis anyway, as an entailment of the CLP predicate either by the incoming state (new design) or the interpolant (old design) does not mean that further symbolic execution from the two different visitations of the callsite would result in the same tree. 

Joxan Jaffar proposed a new approach to use CLP predicate to instead encode the relation between states visited earlier and newly-visited state, without affecting completeness. At the first visit of `klee_join("name", v1, ..., vn)` and successful proof of `name(v1, ..., vn)` we record the values `c1, ..., cn` of `v1, ..., vn`. The next visit of `klee_join("name", v1, ..., v_n)` is considered successful only when a shadow relation `name(v1, ..., vn, c1, ..., cn)` holds. For example, this relation can be used to implement symmetry, e.g., `name(X, Y, Y, X).`
