### ISSUE TITLE
Alternative Behavior of klee_abstract

### ISSUE THREAD

**Issue by domainexpert** [tracer-x/TracerX#92]
@feliciahalim In the design currently being worked on in #86  `klee_abstract(condition(x1, ..., xN))` removes all constraints containing any of `x1`, ..., `xN`, and adds the abstraction condition `condition(x1, ..., xN)` to the path condition. For example, if the state was `x==1 && y==x` and the condition was `x>=1`, this will be abstracted to `x>=1`. An alternative behavior would be to replace `x` (variable in the abstraction condition), with its ghost version, say `ghost_x`, and then adding the path condition, e.g., `ghost_x==1 && y==ghost_x && x>=1`, essentially existentially-quantifying the original `x`. The abstraction is equivalent to `y==1 && x>=1`, which retains the information on `y`. Credit goes to Joxan Jaffar for the idea.

**Comment by feliciahalim** [comment]
@domainexpert Is the transformed formula should be like this?
_`∃x∃y∃ghost_x (ghost_x==1 && y==ghost_x && x>=1)`_

**Comment by domainexpert** [comment]
@feliciahalim It's just _`∃ghost_x (ghost_x==1 && y==ghost_x && x>=1)`_ with `x` and `y` remain unbound.

**Comment by domainexpert** [comment]
@feliciahalim The ghost variables are likely not to be too hard to implement, where we could reuse the substitution mechanism for shadow variables (existentially-quantified variables in subsumption checking).
